[package]
name = "sap_http_session_initializer_windows"
version = "0.0.1"
edition = "2024"
build = "build.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
anyhow = { version = "1" }
serde_json = { version = "1", features = ["default"] }
serde = { version = "1", features = ["default", "derive"] }
chrono = { version = "0", features = ["std", "serde"]}
native-tls = { version = "0.2" }
windows = { version = "0.62", features = [
        "Win32_Security_Cryptography",
        "Win32_Foundation",
        "Win32_Networking_WinHttp",
        "Win32_System_Memory",
        "Win32_System_Diagnostics",
        "Win32_System_Diagnostics_Debug",
        "Win32_System_LibraryLoader",
      ]
}
time = { version = "0.3", features = [ "std" ] }
cookie = { version = "0.18", features = [ "percent-encode" ] }

[build-dependencies]
vergen-gitcl = { version = "9", features = ["build", "cargo"] }

[[bin]]
name = "sap-http-session-initializer"
path = "src/main.rs"